style: devide clone.py to create_training_data.py & train_model.py
atsushi421/ai_challenge_saiI pull request #3
Opened 2022-04-20 11:11 UTC by atsushi421

とりあえず、clone.py を2つのファイルにそのまま分けました。
train_model.py は 引数で .h5 ファイルのパスを指定できるようにしました。

2022-04-20 16:37 UTC, yunicoder requested changes
@atsushi421 

モデルに合わせたリサイズは`create_training_data.py`ではなくて、`train_model.py`でやるようにしたので、[MUST] ってコメントしたとこを追加してみて実行できるか確認してみて欲しい。

他の部分は要相談。

2022-04-20 16:37 UTC, yunicoder commented on train_model.py
> +                        required=True,
必須にしてもいいと思うんだけど、毎回実行するときに指定するの大変かもしれないからdefaultにしてもいいかも。（あ、、でもまだどこに.h5ファイル置くか決めてないか...）

```suggestion
                        default='trainingData.h5'
```

2022-04-20 16:37 UTC, yunicoder commented on create_training_data.py
> +      image = cv2.resize(image, dsize=(480,240)) # for resnet50
[MUST]
create_training_data.pyにモデル情報がないからここ消してtrain_model.pyでリサイズするわ

2022-04-20 16:37 UTC, yunicoder commented on create_training_data.py
> +# MODEL_NAME = RESNET50
この部分なくていいかも

2022-04-20 16:37 UTC, yunicoder commented on train_model.py
> +
[MUST]
リサイズ（画像の前処理）のためのライブラリ読み込み

```suggestion
import cv2
```

2022-04-20 16:37 UTC, yunicoder commented on train_model.py
> +
[MUST]
リサイズ（画像の前処理）の関数の追加

```suggestion

def preprocessing(model, inputs, outputs):

    # resize to fit model input
    images = []
    for input in inputs:
        image = cv2.resize(input, (model.input_shape[2], model.input_shape[1]), interpolation=cv2.INTER_LINEAR)
        images.append(image)

    return np.array(images), outputs
```

2022-04-20 16:37 UTC, yunicoder commented on train_model.py
> +
[MUST]
前処理関数の呼び出し

```suggestion
        
    # preprocessing
    inputs, outputs = preprocessing(model, inputs, outputs)
```

2022-04-22 10:11 UTC, yunicoder commented
### 確認し欲しいこと

以下が動くか
```
# 訓練データ.h5の生成
python create_training_data.py


# モデルの生成
python train_model.py

```

2022-04-22 11:23 UTC, atsushi421 commented
実行確認できた

2022-04-22 11:23 UTC, closed without merging